---
- name: Install dependencies
  become: true
  when: ansible_os_family ==  "Debian"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest

  with_items:
    - libhttp-dav-perl

- name: Install fierce
  become: true
  git:
    repo: https://github.com/cldrn/davtest.git
    dest: "{{ git_location }}/davtest-git"
    update: yes